unit TestCaseSqlGenerator;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, FormExport.SqlGenerator,
  Data.Db, System.SysUtils, Clipbrd,
  Emetra.Logging.Interfaces,
  Emetra.Database.Simple,
  Emetra.Database.Interfaces;

type
  // Test methods for class TFormDumper

  TestTFormDumper = class( TTestCase )
  strict private
    fDb: TSimpleDatabase;
    FFormDumper: TFormDumper;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGenerateSQL;
    procedure TestSaveToCSV;
  end;

implementation

uses
  Emetra.Settings.Test;

const
  FORM_ID_TEST = 912;

procedure TestTFormDumper.SetUp;
begin
  fDb := TSimpleDatabase.Create( GlobalLog );
  FFormDumper := TFormDumper.Create( fDb );
  fDb.ConnectionString := DevConnection;
  fDb.Connect;
end;

procedure TestTFormDumper.TearDown;
begin
  fDb.Disconnect;
  FFormDumper.Free;
  fDb.Free;
end;

procedure TestTFormDumper.TestGenerateSQL;
var
  ReturnValue: string;
begin
  FFormDumper.DateInfo := diNone;
  ReturnValue := FFormDumper.GenerateSQL( FORM_ID_TEST );
  CheckTrue( Pos( 'AgeOnEvent', ReturnValue ) = 0 );
  { Use days }
  FFormDumper.DateInfo := diAgeDays;
  ReturnValue := FFormDumper.GenerateSQL( FORM_ID_TEST );
  CheckTrue( Pos( 'AgeOnEventD', ReturnValue ) > 0 );
  { Use months for extraction }
  FFormDumper.DateInfo := diAgeMonths;
  ReturnValue := FFormDumper.GenerateSQL( FORM_ID_TEST );
  CheckTrue( Pos( 'AgeOnEventM', ReturnValue ) > 0 );
  { Use years }
  FFormDumper.DateInfo := diAgeYears;
  ReturnValue := FFormDumper.GenerateSQL( FORM_ID_TEST );
  CheckTrue( Pos( 'AgeOnEventY', ReturnValue ) > 0 );
end;

procedure TestTFormDumper.TestSaveToCSV;
var
  formId: integer;
  fileName: string;
begin
  formId := FORM_ID_TEST;
  fileName := Format( 'Form-%d.csv', [formId] );
  DeleteFile( fileName );
  FFormDumper.DateInfo := diAgeYears;
  FFormDumper.SaveToCSV( formId );
  CheckTrue( FileExists( fileName ), 'Expected file not found.' );
end;

initialization

// Register any test cases with the test runner
RegisterTest( TestTFormDumper.Suite );

end.
